### ISSUE TITLE
bug in v2 of passport-snyk-oauth2

### ISSUE THREAD

**Issue by dogeared** [snyk/snyk-apps-demo#65]
# Steps to reproduce:

1. check out this branch: https://github.com/snyk/snyk-apps-demo/tree/updated-passport-snyk-oauth2
2. setup your `.env` file as normal
3. npm install as normal
4. run the app as normal: `npm run dev:ts-watch`
5. open an incognito window in chrome
6. authorize snyk
7. close the incognito window in chrome
8. repeat steps 5 and 6

You will see that on the callback from the second time through, you get an authentication failed message.

@clarkio and found that it has something to do with the state and session management. This issue does _not_ occur using the `1.0.x` version of `passport-snyk-oauth2`

## First time through:

<img width="1279" alt="image" src="https://user-images.githubusercontent.com/364562/207458831-cc83667f-33ae-4e20-8459-a16dd1132517.png">

## Second time through:

<img width="641" alt="image" src="https://user-images.githubusercontent.com/364562/207459015-71739649-d44c-4e12-9d83-a205b07f25df.png">

**Comment by jgresty** [comment]
We no longer use `passport-snyk-oauth2` as Snyk Apps can be authed with the plain oauth2 provider. This issue is no longer relevant.
